name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install dependencies
        run: nix develop --command just install

      - name: Lint & Format
        run: nix develop --command just biome-check

      - name: Typecheck
        run: nix develop --command just tsc

      - name: Rust format
        run: nix develop --command just cargo-fmt

      - name: Rust clippy
        run: nix develop --command just cargo-clippy

      - name: Rust tests
        run: nix develop --command just cargo-test
